-- CREATE TABLE IF NOT EXISTS users
-- (
-- 	id INT NOT NULL AUTO_INCREMENT,
-- 	login VARCHAR(255) NOT NULL,
-- 	password VARCHAR(255) NOT NULL,
-- 	PRIMARY KEY (id)
-- );
-- CREATE TABLE IF NOT EXISTS statuses
-- (
-- 	id INT NOT NULL AUTO_INCREMENT,
-- 	content VARCHAR(255) NOT NULL,
-- 	date DATE,
-- 	user_id INT,
-- 	PRIMARY KEY (id),
-- 	CONSTRAINT fk_UserId
-- 	FOREIGN KEY (user_id) REFERENCES users(id)
-- );

CREATE TABLE IF NOT EXISTS users
(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	login VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS statuses
(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	content VARCHAR(255) NOT NULL,
	date DATE,
	user_id INT,
	CONSTRAINT fk_UserId
	FOREIGN KEY (user_id) REFERENCES users(id)
);